In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('/kaggle/input/datasets/sourav2083/class-dataset-movies/movie_prediction_dataset_final.csv')

In [15]:
print(df.isnull().sum())

release_year                 0
budget                       0
runtime                      0
is_sequel                    0
director_name                0
director_popularity          0
lead_actor1                  0
lead_actor1_popularity       0
primary_genre                0
genre2                     535
studio_1                     0
studio_2                   501
brand_name                   0
mpaa_rating                  0
release_month                0
is_holiday_release           0
Distributor               1314
First_Week_Income         1344
dtype: int64

In [16]:
df.head()

,release_year,budget,runtime,is_sequel,director_name,director_popularity,lead_actor1,lead_actor1_popularity,primary_genre,genre2,studio_1,studio_2,brand_name,mpaa_rating,release_month,is_holiday_release,Distributor,First_Week_Income
0,2009,40000000,111,0,Mira Nair,1.3916,Hilary Swank,2.2810,Adventure,Drama,AE Electra Productions,Fox Searchlight Pictures,General,PG,10,0,Fox Searchlight Pictures,5305832.0
1,2009,237000000,162,1,James Cameron,4.3403,Sam Worthington,4.0107,Action,Adventure,Dune Entertainment,Lightstorm Entertainment,Avatar,PG-13,12,1,Twentieth Century Fox,137094051.0
2,2009,60000000,100,0,Henry Selick,1.6349,Dakota Fanning,7.9341,Animation,Family,LAIKA,Pandemonium,General,PG,2,0,Focus Features,20235921.0
3,2009,175000000,96,0,Pete Docter,1.3480,Ed Asner,1.4701,Animation,Comedy,Pixar,NaN,General,PG,5,0,Walt Disney Studios Motion Pictures,93072435.0
4,2009,70000000,153,0,Quentin Tarantino,3.8346,Brad Pitt,9.0310,Drama,Thriller,Universal Pictures,The Weinstein Company,General,R,8,0,The Weinstein Company,53703427.0

In [17]:
df['genre2'] = df['genre2'].fillna('Unknown')
print(df.isnull().sum())

release_year                 0
budget                       0
runtime                      0
is_sequel                    0
director_name                0
director_popularity          0
lead_actor1                  0
lead_actor1_popularity       0
primary_genre                0
genre2                       0
studio_1                     0
studio_2                   501
brand_name                   0
mpaa_rating                  0
release_month                0
is_holiday_release           0
Distributor               1314
First_Week_Income         1344
dtype: int64

In [18]:
df['studio_2'] = df['studio_2'].fillna('None')
print(df.isnull().sum())

release_year                 0
budget                       0
runtime                      0
is_sequel                    0
director_name                0
director_popularity          0
lead_actor1                  0
lead_actor1_popularity       0
primary_genre                0
genre2                       0
studio_1                     0
studio_2                     0
brand_name                   0
mpaa_rating                  0
release_month                0
is_holiday_release           0
Distributor               1314
First_Week_Income         1344
dtype: int64

In [19]:
most_occured_distributor = df['Distributor'].mode()
print(most_occured_distributor)

0    Warner Bros.
Name: Distributor, dtype: object

In [20]:
df['Distributor'] = df['Distributor'].fillna('Warner Bros')

In [21]:
df = df.dropna(subset=['First_Week_Income'])

In [22]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 2246 entries, 0 to 3589
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   release_year            2246 non-null   int64
 1   budget                  2246 non-null   int64
 2   runtime                 2246 non-null   int64
 3   is_sequel               2246 non-null   int64
 4   director_name           2246 non-null   object
 5   director_popularity     2246 non-null   float64
 6   lead_actor1             2246 non-null   object
 7   lead_actor1_popularity  2246 non-null   float64
 8   primary_genre           2246 non-null   object
 9   genre2                  2246 non-null   object
 10  studio_1                2246 non-null   object
 11  studio_2                2246 non-null   object
 12  brand_name              2246 non-null   object
 13  mpaa_rating             2246 non-null   object
 14  release_month           2246 non-null   int64
 15  is_holiday_release      2246 non-null   int64
 16  Distributor             2246 non-null   object
 17  First_Week_Income       2246 non-null   float64
dtypes: float64(3), int64(6), object(9)
memory usage: 333.4+ KB
None

In [23]:
print(df.duplicated().sum())

9

In [24]:
df = df.drop_duplicates()

In [25]:
print(df.duplicated().sum())

0

In [26]:
df['is_sequel'] = df['is_sequel'].astype('int')

In [27]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 2237 entries, 0 to 3589
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   release_year            2237 non-null   int64
 1   budget                  2237 non-null   int64
 2   runtime                 2237 non-null   int64
 3   is_sequel               2237 non-null   int64
 4   director_name           2237 non-null   object
 5   director_popularity     2237 non-null   float64
 6   lead_actor1             2237 non-null   object
 7   lead_actor1_popularity  2237 non-null   float64
 8   primary_genre           2237 non-null   object
 9   genre2                  2237 non-null   object
 10  studio_1                2237 non-null   object
 11  studio_2                2237 non-null   object
 12  brand_name              2237 non-null   object
 13  mpaa_rating             2237 non-null   object
 14  release_month           2237 non-null   int64
 15  is_holiday_release      2237 non-null   int64
 16  Distributor             2237 non-null   object
 17  First_Week_Income       2237 non-null   float64
dtypes: float64(3), int64(6), object(9)
memory usage: 332.1+ KB
None

In [28]:
print(df.nunique())

release_year                17
budget                     279
runtime                    106
is_sequel                    2
director_name             1211
director_popularity       1167
lead_actor1               1016
lead_actor1_popularity    1007
primary_genre               18
genre2                      19
studio_1                   863
studio_2                   954
brand_name                 418
mpaa_rating                  5
release_month               12
is_holiday_release           2
Distributor                126
First_Week_Income         2222
dtype: int64

In [29]:
df_encoded = pd.get_dummies(df, columns=['primary_genre'], drop_first=True)

df_encoded.head()

,release_year,budget,runtime,is_sequel,director_name,director_popularity,lead_actor1,lead_actor1_popularity,genre2,studio_1,...,primary_genre_Fantasy,primary_genre_History,primary_genre_Horror,primary_genre_Music,primary_genre_Mystery,primary_genre_Romance,primary_genre_Science Fiction,primary_genre_Thriller,primary_genre_War,primary_genre_Western
0,2009,40000000,111,0,Mira Nair,1.3916,Hilary Swank,2.2810,Drama,AE Electra Productions,...,False,False,False,False,False,False,False,False,False,False
1,2009,237000000,162,1,James Cameron,4.3403,Sam Worthington,4.0107,Adventure,Dune Entertainment,...,False,False,False,False,False,False,False,False,False,False
2,2009,60000000,100,0,Henry Selick,1.6349,Dakota Fanning,7.9341,Family,LAIKA,...,False,False,False,False,False,False,False,False,False,False
3,2009,175000000,96,0,Pete Docter,1.3480,Ed Asner,1.4701,Comedy,Pixar,...,False,False,False,False,False,False,False,False,False,False
4,2009,70000000,153,0,Quentin Tarantino,3.8346,Brad Pitt,9.0310,Thriller,Universal Pictures,...,False,False,False,False,False,False,False,False,False,False

In [31]:
df_encoded2 = pd.get_dummies(df, columns=['mpaa_rating'], drop_first=True)

df_encoded2.head()

,release_year,budget,runtime,is_sequel,director_name,director_popularity,lead_actor1,lead_actor1_popularity,primary_genre,genre2,...,studio_2,brand_name,release_month,is_holiday_release,Distributor,First_Week_Income,mpaa_rating_NR,mpaa_rating_PG,mpaa_rating_PG-13,mpaa_rating_R
0,2009,40000000,111,0,Mira Nair,1.3916,Hilary Swank,2.2810,Adventure,Drama,...,Fox Searchlight Pictures,General,10,0,Fox Searchlight Pictures,5305832.0,False,True,False,False
1,2009,237000000,162,1,James Cameron,4.3403,Sam Worthington,4.0107,Action,Adventure,...,Lightstorm Entertainment,Avatar,12,1,Twentieth Century Fox,137094051.0,False,False,True,False
2,2009,60000000,100,0,Henry Selick,1.6349,Dakota Fanning,7.9341,Animation,Family,...,Pandemonium,General,2,0,Focus Features,20235921.0,False,True,False,False
3,2009,175000000,96,0,Pete Docter,1.3480,Ed Asner,1.4701,Animation,Comedy,...,None,General,5,0,Walt Disney Studios Motion Pictures,93072435.0,False,True,False,False
4,2009,70000000,153,0,Quentin Tarantino,3.8346,Brad Pitt,9.0310,Drama,Thriller,...,The Weinstein Company,General,8,0,The Weinstein Company,53703427.0,False,False,False,True

In [32]:
df_encoded2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2237 entries, 0 to 3589
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   release_year            2237 non-null   int64
 1   budget                  2237 non-null   int64
 2   runtime                 2237 non-null   int64
 3   is_sequel               2237 non-null   int64
 4   director_name           2237 non-null   object
 5   director_popularity     2237 non-null   float64
 6   lead_actor1             2237 non-null   object
 7   lead_actor1_popularity  2237 non-null   float64
 8   primary_genre           2237 non-null   object
 9   genre2                  2237 non-null   object
 10  studio_1                2237 non-null   object
 11  studio_2                2237 non-null   object
 12  brand_name              2237 non-null   object
 13  release_month           2237 non-null   int64
 14  is_holiday_release      2237 non-null   int64
 15  Distributor             2237 non-null   object
 16  First_Week_Income       2237 non-null   float64
 17  mpaa_rating_NR          2237 non-null   bool
 18  mpaa_rating_PG          2237 non-null   bool
 19  mpaa_rating_PG-13       2237 non-null   bool
 20  mpaa_rating_R           2237 non-null   bool
dtypes: bool(4), float64(3), int64(6), object(8)
memory usage: 323.3+ KB

In [33]:
df_final = df_encoded2.drop(columns=['genre2'])

df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2237 entries, 0 to 3589
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   release_year            2237 non-null   int64
 1   budget                  2237 non-null   int64
 2   runtime                 2237 non-null   int64
 3   is_sequel               2237 non-null   int64
 4   director_name           2237 non-null   object
 5   director_popularity     2237 non-null   float64
 6   lead_actor1             2237 non-null   object
 7   lead_actor1_popularity  2237 non-null   float64
 8   primary_genre           2237 non-null   object
 9   studio_1                2237 non-null   object
 10  studio_2                2237 non-null   object
 11  brand_name              2237 non-null   object
 12  release_month           2237 non-null   int64
 13  is_holiday_release      2237 non-null   int64
 14  Distributor             2237 non-null   object
 15  First_Week_Income       2237 non-null   float64
 16  mpaa_rating_NR          2237 non-null   bool
 17  mpaa_rating_PG          2237 non-null   bool
 18  mpaa_rating_PG-13       2237 non-null   bool
 19  mpaa_rating_R           2237 non-null   bool
dtypes: bool(4), float64(3), int64(6), object(7)
memory usage: 305.8+ KB

In [35]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
ord = OrdinalEncoder()

In [37]:
df['Distributor'] = ord.fit_transform(df[['Distributor']])

df.head()

,release_year,budget,runtime,is_sequel,director_name,director_popularity,lead_actor1,lead_actor1_popularity,primary_genre,genre2,studio_1,studio_2,brand_name,mpaa_rating,release_month,is_holiday_release,Distributor,First_Week_Income
0,2009,40000000,111,0,Mira Nair,1.3916,Hilary Swank,2.2810,Adventure,Drama,AE Electra Productions,Fox Searchlight Pictures,General,PG,10,0,40.0,5305832.0
1,2009,237000000,162,1,James Cameron,4.3403,Sam Worthington,4.0107,Action,Adventure,Dune Entertainment,Lightstorm Entertainment,Avatar,PG-13,12,1,110.0,137094051.0
2,2009,60000000,100,0,Henry Selick,1.6349,Dakota Fanning,7.9341,Animation,Family,LAIKA,Pandemonium,General,PG,2,0,37.0,20235921.0
3,2009,175000000,96,0,Pete Docter,1.3480,Ed Asner,1.4701,Animation,Comedy,Pixar,None,General,PG,5,0,118.0,93072435.0
4,2009,70000000,153,0,Quentin Tarantino,3.8346,Brad Pitt,9.0310,Drama,Thriller,Universal Pictures,The Weinstein Company,General,R,8,0,108.0,53703427.0